INFO - 2024-05-22 15:59:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 15:59:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 16:03:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:03:46 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
INFO - 2024-05-22 16:10:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:10:47 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
INFO - 2024-05-22 16:14:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:14:26 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-22 16:14:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'categorias' already exists
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 2 APPPATH\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
 3 SYSTEMPATH\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
 4 SYSTEMPATH\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
 5 APPPATH\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-22 16:14:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'categorias' already exists
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 3 SYSTEMPATH\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 4 APPPATH\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
 5 SYSTEMPATH\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
 6 SYSTEMPATH\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
 7 APPPATH\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-22 16:14:26 --> [Caused by] mysqli_sql_exception: Table 'categorias' already exists
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 4 SYSTEMPATH\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 5 APPPATH\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
 6 SYSTEMPATH\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
 7 SYSTEMPATH\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
 8 APPPATH\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-05-22 16:15:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:15:10 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
INFO - 2024-05-22 16:19:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:19:59 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
INFO - 2024-05-22 16:20:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:20:12 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
INFO - 2024-05-22 16:20:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:20:14 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
INFO - 2024-05-22 16:20:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:20:43 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2024-05-22 16:22:04 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-21-205238_CreaTablaCategorias.php(24): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
INFO - 2024-05-22 16:40:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:40:39 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-22-162642_CreaTablaCategorias.php(23): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-22 16:46:28 --> ErrorException: Uncaught mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-22-162642_CreaTablaCategorias.php(23): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:313
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-22-162642_CreaTablaCategorias.php(23): CodeIgniter\Database\Forge->createTable('categorias')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
  thrown
[Method: GET, Route: /]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2024-05-22 16:46:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 16:47:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 16:47:21 --> mysqli_sql_exception: Table 'categorias' already exists in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `c...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `c...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `c...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `c...')
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Migrations\2024-05-22-162642_CreaTablaCategorias.php(23): CodeIgniter\Database\Forge->createTable('categorias')
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(933): App\Controllers\Home->index()
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-05-22 16:47:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'categorias' already exists
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 2 APPPATH\Database\Migrations\2024-05-22-162642_CreaTablaCategorias.php(23): CodeIgniter\Database\Forge->createTable('categorias')
 3 SYSTEMPATH\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
 4 SYSTEMPATH\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
 5 APPPATH\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-22 16:47:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'categorias' already exists
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 3 SYSTEMPATH\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 4 APPPATH\Database\Migrations\2024-05-22-162642_CreaTablaCategorias.php(23): CodeIgniter\Database\Forge->createTable('categorias')
 5 SYSTEMPATH\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
 6 SYSTEMPATH\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
 7 APPPATH\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-22 16:47:22 --> [Caused by] mysqli_sql_exception: Table 'categorias' already exists
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 4 SYSTEMPATH\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `categorias` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	CONSTRAINT `pk_categorias` PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci')
 5 APPPATH\Database\Migrations\2024-05-22-162642_CreaTablaCategorias.php(23): CodeIgniter\Database\Forge->createTable('categorias')
 6 SYSTEMPATH\Database\MigrationRunner.php(867): App\Database\Migrations\CreaTablaCategorias->up()
 7 SYSTEMPATH\Database\MigrationRunner.php(183): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
 8 APPPATH\Controllers\Home.php(13): CodeIgniter\Database\MigrationRunner->latest()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-05-22 16:49:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 16:51:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:10:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:14:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:14:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:14:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:14:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:16:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:16:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:16:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:16:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:16:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:16:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:16:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:18:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:18:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:18:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:28:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-22 17:30:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-22 18:29:56 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `ca...', 0)
#1 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseBuilder.php(1821): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', NULL, false)
#4 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\BaseBuilder.php(2210): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\app\Database\Seeds\CategoriasSeeder.php(20): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Database\Seeder.php(147): App\Database\Seeds\CategoriasSeeder->run()
#7 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\EjerciciosdeCodeIgniter\codeIgniter\ejercicio1\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
